---
title: "Inflammasome activation in macrophages is regulated by actin-bundling protein L-plastin"
collection: publications
category: manuscripts
permalink: /publication/inflammasome-l-plastin
excerpt: 'Macrophage secretion of IL-1β is crucial to combat and clear bacterial infections. IL-1β release is tightly controlled by assembly of multimolecular inflammasomes (i.e. NLRP3, NLRC4, AIM2) and irregulated production can contribute to various pathologic conditions (i.e. acute respiratory disease and ventilator-associated lung injury). Prior research suggests that mechanical stress elevates macrophage IL-1β production. Because increased lung stiffness in diseases (e.g. acute respiratory distress syndrome) exerts mechanical stress on residing alveolar macrophages (AMs). Understanding how mechanical stress modulates AMs becomes crucial to elucidating the pathophysiology of pulmonary disease. We observed that IL-1β production in AMs was abrogated in absence of L-plastin (LPL), a hematopoietic restricted actin-bundling protein. LPL is also required for podosome formation. Podosomes are integrin-based, adhesive and mechanosensitive signaling organelles. LPL-deficient macrophages showed decreased IL-1β production when cultured on varying substrate stiffness. These observations suggest that LPL may link contact-based mechanosensation to inflammasome activation. Additionally, Pneumolysin toxin in Streptococcus pneumoniae infection activates NLRP3 and may exacerbate inflammatory pathogenesis in stiffened lungs. Further, we will investigate LPL mediated mechano-sensitive inflammasome activation in pneumococcal lung infections using mouse models. Our observations indicate previously unknown mechanosensitive pathway for inflammasome activation in macrophages. Understanding the molecular mechanism will aid in developing immunomodulatory therapies to treat inflammatory disorders and diseases.'
date: 2019-05-01
venue: 'The Journal of Immunology'
paperurl: 'https://doi.org/10.4049/jimmunol.202.Supp.117.14'
citation: 'Hemant Joshi, Betsy Elisabeth Todd, **Taylor Szasz**, Edgar Anaya, Sharon Celeste Morley; Inflammasome activation in macrophages is regulated by actin-bundling protein L-plastin. J Immunol 1 May 2019; 202 (1_Supplement): 117.14. https://doi.org/10.4049/jimmunol.202.Supp.117.14'
---

The contents above will be part of a list of publications, if the user clicks the link for the publication than the contents of section will be rendered as a full page, allowing you to provide more information about the paper for the reader. When publications are displayed as a single page, the contents of the above "citation" field will automatically be included below this section in a smaller font.
